{"level":"error","message":"Unable to connect to the database: database \"makrochain\" does not exist","name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":95,"line":"947","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":95,"line":"947","name":"error","routine":"InitPostgres","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: database \"makrochain\" does not exist\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:25:25"}
{"level":"error","message":"Server initialization failed: database \"makrochain\" does not exist","service":"makrochain-backend","timestamp":"2025-03-11 15:25:25"}
{"level":"error","message":"Unable to connect to the database: database \"makronexus\" does not exist","name":"SequelizeConnectionError","original":{"code":"3D000","file":"postinit.c","length":95,"line":"947","name":"error","routine":"InitPostgres","severity":"FATAL"},"parent":{"code":"3D000","file":"postinit.c","length":95,"line":"947","name":"error","routine":"InitPostgres","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: database \"makronexus\" does not exist\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:34:00"}
{"level":"error","message":"Server initialization failed: database \"makronexus\" does not exist","service":"makrochain-backend","timestamp":"2025-03-11 15:34:00"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:44:37"}
{"level":"error","message":"Server initialization failed: password authentication failed for user \"postgres\"","service":"makrochain-backend","timestamp":"2025-03-11 15:44:37"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:45:26"}
{"level":"error","message":"Server initialization failed: password authentication failed for user \"postgres\"","service":"makrochain-backend","timestamp":"2025-03-11 15:45:26"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:49:20"}
{"level":"error","message":"Server initialization failed: password authentication failed for user \"postgres\"","service":"makrochain-backend","timestamp":"2025-03-11 15:49:20"}
{"level":"error","message":"Unable to connect to the database: password authentication failed for user \"postgres\"","name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":104,"line":"329","name":"error","routine":"auth_failed","severity":"FATAL"},"service":"makrochain-backend","stack":"SequelizeConnectionError: password authentication failed for user \"postgres\"\n    at Client._connectionCallback (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:326:19)\n    at Client._handleErrorMessage (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\client.js:346:19)\n    at Connection.emit (node:events:517:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\siuol\\OneDrive\\Documents\\MakroChain_BE\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:517:28)\n    at Socket.emit (node:domain:489:12)","timestamp":"2025-03-11 15:50:44"}
{"level":"error","message":"Server initialization failed: password authentication failed for user \"postgres\"","service":"makrochain-backend","timestamp":"2025-03-11 15:50:44"}
